import {todo} from "./logic/factory.js";
import {app} from "./logic/app.js";
import {project} from "./logic/project.js";
import { projectUi } from "./UI/projectUI.js";
import { todoUi } from "./UI/todoUI.js";
const cont = new app();
const render = new projectUi(cont);
const rendertodo = new todoUi(cont);
cont.createproject("work");
cont.createproject("school");
cont.createproject("home");
console.log(cont.projects);
cont.createtodo("work","shopping", "food", "2025-5-28", "high");
console.log(cont.projects);
console.log(cont.projects);
cont.getprojects("school");
cont.changepriority("work", "shopping", "low");
console.log(cont.projects)
console.log(cont.getprojects());
console.log(render.renderSidebar());
console.log(render.projectform("schol"));
cont.createtodo("schol", "reading", "physicss", "2025-9-17", "low");
console.log(cont.findproject("schol"));
cont.changepriority("schol", "reading", "high");
cont.createtodo("schol", "washing", "jeans", "2025-9-17", "low");
console.log(rendertodo.rendertodos("schol"));
cont.createproject("coding");
rendertodo.formtodo("coding", "html", "html", "2026-3-30", "medium");
rendertodo.formtodo("coding", "css", "css", "2026-3-30", "medium");
rendertodo.formtodo("coding", "js", "js", "2026-3-30", "medium");
console.log(rendertodo.rendertodos("coding"));
cont.setTodoComplete("coding", "html");
cont.setTodoComplete("coding", "html");
console.log(rendertodo.tododetails("coding"));
rendertodo.deletetodo("coding", "js");
console.log(rendertodo.rendertodos("coding"));
rendertodo.completetodo("coding", "css");
rendertodo.completetodo("coding", "css");
